## Machine Learning Algorithm _ LinearModels 과제(고준영, 박세현, 이동현, 정에녹)
---

# 라이브러리 임포트

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# 분류를 위한 데이터셋 생성

### VARK Learning Styles loading

VARK Learning Styles

There are many different ways of categorizing learning styles, but Neil Fleming's VARK model is one of the most popular. Fleming introduced an inventory in 1987 that was designed to help students and others 
learn more about their individual learning preferences.

According to the VARK model, learners are identified by whether they have a preference for:

- Visual learning (pictures, movies, diagrams)
- Auditory learning (music, discussion, lectures)
- Reading and writing (making lists, reading textbooks, taking notes) (*해당 데이터에선 생략)
- Kinesthetic learning (movement, experiments, hands-on activities)

In [19]:
student_learning_style = pd.read_csv("./SL_csv.csv")
student_learning_style

Gender  Age  \
0       Male   16   
1       Male   16   
2       Male   18   
3       Male   21   
4     Female   21   
...      ...  ...   
1205    Male   17   
1206    Male   18   
1207    Male   19   
1208  Female   17   
1209    Male   16   

      I learn better by reading what the teacher writes on the chalkboard.  \
0                                                     3                      
1                                                     5                      
2                                                     3                      
3                                                     1                      
4                                                     4                      
...                                                 ...                      
1205                                                  2                      
1206                                                  5                      
1207                                                  4                      
1208                                                  2                      
1209                                                  4                      

      When I read instructions, I remember them better.  \
0                                                     3   
1                                                     4   
2                                                     4   
3                                                     3   
4                                                     4   
...                                                 ...   
1205                                                  3   
1206                                                  2   
1207                                                  4   
1208                                                  3   
1209                                                  3   

      I understand better when I read instructions.  \
0                                                 4   
1                                                 4   
2                                                 3   
3                                                 3   
4                                                 4   
...                                             ...   
1205                                              3   
1206                                              4   
1207                                              5   
1208                                              5   
1209                                              3   

      I learn better by reading than by listening to someone.  \
0                                                     3         
1                                                     4         
2                                                     3         
3                                                     4         
4                                                     5         
...                                                 ...         
1205                                                  4         
1206                                                  3         
1207                                                  3         
1208                                                  4         
1209                                                  5         

      I learn more by reading textbooks than by listening to lectures.  \
0                                                     2                  
1                                                     3                  
2                                                     4                  
3                                                     4                  
4                                                     5                  
...                                                 ...                  
1205                                                  4                  
1206                                                  3                  

In [31]:
X = student_learning_style.iloc[:, 2:-2]
y = student_learning_style.iloc[:, -1]

In [25]:
np.unique(y)

array(['A', 'K', 'V'], dtype=object)

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=0)

## LogisticRegression hyperparams

In [80]:
from sklearn.linear_model import LogisticRegression

hyperparams = {
    "penalty": "none",                      # 데이터 L1, L2 패널티 적용 관련
    "C": 1.0,                               # regularization 강도
    "fit_intercept": True,
    "class_weight": {"A":1, "K":1, "V":1},  # 클래스 가중치
    "solver": "lbfgs",                      # optimizer 알고리즘, lbfgs의 경우 L2 패널티 적용 되어야 한다      
    "max_iter": 500,                        
    "verbose": 0,                           # 학습로그 출력 횟수
    "random_state": 0,          
    "n_jobs": -1
}

'''
penalty: str = "l2", *, 
dual: bool = False, 
tol: float = 0.0001, 
C: float = 1, 
fit_intercept: bool = True, 
intercept_scaling: int = 1, 
class_weight: Any | None = None, 
random_state: Any | None = None, 
solver: str = "lbfgs", 
max_iter: int = 100, 
multi_class: str = "auto", 
verbose: int = 0, 
warm_start: bool = False, 
n_jobs: Any | None = None, 
l1_ratio: Any | None = None) -> None
'''

model = LogisticRegression(**hyperparams)
model

LogisticRegression(class_weight={'A': 1, 'K': 1, 'V': 1}, max_iter=500,
                   n_jobs=-1, penalty='none', random_state=0)

### 모델 학습

In [ ]:
model.fit(X_train, y_train)

train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

train_score, test_score

### Attributes 확인

In [43]:
model.classes_

array(['A', 'K', 'V'], dtype=object)

In [40]:
model.coef_

array([[ 1.48645923,  1.25675269,  1.21397988,  1.13234598,  1.3465146 ,
        -0.92627913, -1.04490046, -0.991945  , -0.89940454, -0.96034919,
        -0.33261105, -0.47635634, -0.38568974, -0.3829687 ],
       [-0.45234276, -0.42218325, -0.358166  , -0.31163   , -0.44160785,
        -0.50457059, -0.17612449, -0.356389  , -0.34600583, -0.43361548,
         0.89760847,  1.04817521,  1.02113771,  0.96012768],
       [-1.03411648, -0.83456944, -0.85581389, -0.82071597, -0.90490675,
         1.43084971,  1.22102494,  1.348334  ,  1.24541037,  1.39396467,
        -0.56499742, -0.57181887, -0.63544797, -0.57715898]])

In [42]:
model.intercept_

array([-0.73370862,  1.21231774, -0.47860912])

In [41]:
model.feature_names_in_

array(['I learn better by reading what the teacher writes on the chalkboard.',
       'When I read instructions, I remember them better.',
       'I understand better when I read instructions.',
       'I learn better by reading than by listening to someone.',
       'I learn more by reading textbooks than by listening to lectures.',
       'When the teacher tells me the instructions I understand better',
       'When someone tells me how to do something in class, I learn it better.',
       'I remember things I have heard in class better than things I have read.',
       'I learn better in class when the teacher gives a lecture.',
       'I learn better in class when I listen to someone.',
       'I prefer to learn by doing something in class.',
       'When I do things in class, I learn better.',
       'I enjoy learning in class by doing experiments.',
       'I understand things better in class when I participate in role-playing.'],
      dtype=object)

In [44]:
model.n_iter_

array([100], dtype=int32)

In [75]:
print(f"{model.classes_[0]} = ")
for coef, feature in zip(model.coef_[0], model.feature_names_in_):
    print(f"    {coef} * [{feature}] + ")
print(f"    {model.intercept_[0]}")

A = 
    1.7357020627426025 * [I learn better by reading what the teacher writes on the chalkboard.] + 
    1.5179653476707737 * [When I read instructions, I remember them better.] + 
    1.4488438005700148 * [I understand better when I read instructions.] + 
    1.3553589309729281 * [I learn better by reading than by listening to someone.] + 
    1.5778830500449992 * [I learn more by reading textbooks than by listening to lectures.] + 
    -1.130008466359626 * [When the teacher tells me the instructions I understand better] + 
    -1.2496312345020029 * [When someone tells me how to do something in class, I learn it better.] + 
    -1.1743104925319034 * [I remember things I have heard in class better than things I have read.] + 
    -1.0869700533309963 * [I learn better in class when the teacher gives a lecture.] + 
    -1.1440765957972379 * [I learn better in class when I listen to someone.] + 
    -0.36391601728717005 * [I prefer to learn by doing something in class.] + 
    -0.55254

## Ridge(Classifier) hyperparams

In [99]:
from sklearn.linear_model import RidgeClassifier


hyperparams = {
    'alpha': 1.0,               # Regularization strength;
    'fit_intercept': False,     # bias 계산 여부
    'copy_X': True,             # X will be copied if copy_X is True
    'max_iter': 200,            # Maximum number of iterations for conjugate gradient solver
    'tol': 0.001,               # Precision of the solution.
    'solver': 'sag',            # Calculation policy, auto’ chooses the solver automatically based on the type of data
    'random_state': 0           # Loading same data from given number (Used when solver == ‘sag’ or ‘saga’ to shuffle the data.)
}

'''
alpha: float = 1, *,
fit_intercept: bool = True,
normalize: str = "deprecated", 
copy_X: bool = True, 
max_iter: Any | None = None, 
tol: float = 0.001, 
class_weight: Any | None = None,
solver: str = "auto", 
positive: bool = False, 
random_state: Any | None = None
'''

ridge_classifier = RidgeClassifier(**hyperparams)
ridge_classifier

RidgeClassifier(fit_intercept=False, max_iter=200, random_state=0, solver='sag')

In [100]:
ridge_classifier.fit(X_train, y_train)

train_score = ridge_classifier.score(X_train, y_train)
test_score = ridge_classifier.score(X_test, y_test)

train_score, test_score

(0.8276269185360094, 0.8292011019283747)

### attributes

In [96]:
ridge_classifier.coef_

array([[ 0.20463225,  0.17123407,  0.17578657,  0.11727753,  0.15441331,
        -0.07626511, -0.10550042, -0.07196038, -0.12284394, -0.12653149,
        -0.11336026, -0.09133679, -0.11175089, -0.12526283],
       [-0.08013621, -0.12009499, -0.10579307, -0.05231711, -0.0851476 ,
        -0.11947198, -0.06078319, -0.12140521, -0.05700269, -0.09749046,
         0.22924311,  0.17226534,  0.25465786,  0.23679844],
       [-0.15537164, -0.07233084, -0.09132398, -0.09909823, -0.09667612,
         0.18461558,  0.14645031,  0.16534947,  0.17563956,  0.21218715,
        -0.12522134, -0.09966525, -0.16637277, -0.13769765]])

In [97]:
ridge_classifier.intercept_ # hyperparams fit_intercept = False의 결과

0.0

In [101]:
ridge_classifier.n_iter_                # solver == auto로 해당값 None, sag이면 다음과 같다.

array([27, 27, 23], dtype=int32)

In [83]:
ridge_classifier.classes_

array(['A', 'K', 'V'], dtype='<U1')

In [89]:
ridge_classifier.n_features_in_

14

In [91]:
ridge_classifier.n_features_in_ == X_train.shape[1]

True

In [86]:
ridge_classifier.feature_names_in_

array(['I learn better by reading what the teacher writes on the chalkboard.',
       'When I read instructions, I remember them better.',
       'I understand better when I read instructions.',
       'I learn better by reading than by listening to someone.',
       'I learn more by reading textbooks than by listening to lectures.',
       'When the teacher tells me the instructions I understand better',
       'When someone tells me how to do something in class, I learn it better.',
       'I remember things I have heard in class better than things I have read.',
       'I learn better in class when the teacher gives a lecture.',
       'I learn better in class when I listen to someone.',
       'I prefer to learn by doing something in class.',
       'When I do things in class, I learn better.',
       'I enjoy learning in class by doing experiments.',
       'I understand things better in class when I participate in role-playing.'],
      dtype=object)

# 회귀를 위한 데이터셋 생성

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

def make_wave(n_samples=100):
    rnd = np.random.RandomState(42)
    x = rnd.uniform(-3, 3, size=n_samples)
    y_no_noise = (np.sin(4 * x) + x)
    y = (y_no_noise + rnd.normal(size=len(x))) / 2
    return x.reshape(-1, 1), y

X, y = make_wave(60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

## LinearRegression hyperparams

In [186]:
from sklearn.linear_model import LinearRegression


hyperparams = {
    "fit_intercept": True,
    "copy_X": True,
    "n_jobs": -1,
    "positive": True
}

'''
*, 
fit_intercept: bool = True, 
normalize: str = "deprecated", 
copy_X: bool = True, 
n_jobs: Any | None = None, 
positive: bool = False
'''


linear_model = LinearRegression(**hyperparams)
linear_model

LinearRegression(n_jobs=-1, positive=True)

In [189]:
linear_model.fit(X_train, y_train)

train_score = linear_model.score(X_train, y_train)
test_score = linear_model.score(X_test, y_test)

train_score, test_score

(0.6700890315075756, 0.65933685968637)

### attributes

In [190]:
linear_model.coef_

array([0.39390555])

In [195]:
linear_model.rank_              # X의 행렬 순위,  X가 dense 할 때만 값 반환

AttributeError: 'LinearRegression' object has no attribute 'rank_'

In [193]:
linear_model.singular_          # X의 특이값 검색,  X가 dense 할 때만 값 반환

AttributeError: 'LinearRegression' object has no attribute 'singular_'

In [191]:
linear_model.intercept_

-0.03180434302675976

In [192]:
linear_model.n_features_in_

1

## Lasso hyperparams

In [183]:
from sklearn.linear_model import Lasso

hyperparams = {
    "alpha": 0.0001,            # Regularization strength;
    "fit_intercept": True,      # bias 계산 여부
    "precompute": False, 
    "copy_X": True,             # X will be copied if copy_X is True
    "max_iter": 1000,           # Maximum number of iterations for conjugate gradient solver
    "tol": 0.0001,              # Precision of the solution.
    "warm_start": True,         # True로 설정하면 이전 가중치를 활용
    "positive": False,          # bias 값을 양수로 설정
    "random_state": 0, 
    "selection":"random"       
}

'''
alpha: float = 1, *, 
fit_intercept: bool = True,
normalize: str = "deprecated", 
precompute: bool = False, 
copy_X: bool = True, 
max_iter: int = 1000, 
tol: float = 0.0001, 
warm_start: bool = False, 
positive: bool = False, 
random_state: Any | None = None, 
selection: str = "cyclic"
'''

lasso_model = Lasso(**hyperparams)
lasso_model

Lasso(alpha=0.0001, random_state=0, selection='random', warm_start=True)

In [184]:
lasso_model.fit(X_train, y_train)

train_score = lasso_model.score(X_train, y_train)
test_score = lasso_model.score(X_test, y_test)

train_score, test_score

(0.6700890276595683, 0.6593193368604192)

### attributes

In [177]:
lasso_model.coef_

array([0.3938757])

In [178]:
lasso_model.dual_gap_

3.947459643111668e-17

In [179]:
lasso_model.intercept_

-0.03181338502683505

In [180]:
lasso_model.n_features_in_

1

In [160]:
lasso_model.feature_names_in_       # X에 feature 이름이 있어야만 한다.

AttributeError: 'Lasso' object has no attribute 'feature_names_in_'