In [1]:
# 으뜸 머신러닝 심화문제 3.1

import numpy as np

new_array = np.random.randint(9, size=(10000,10000))
print(new_array)

# 1)
plus = new_array +1
print(plus)

# 2)
plus[0::2] = 0
print(plus)

# 3)
plus[0:,1::2] = 0
print(plus)

[[4 3 1 ... 6 1 0]
 [4 8 1 ... 7 8 5]
 [7 7 0 ... 4 0 2]
 ...
 [7 6 2 ... 6 1 0]
 [8 4 2 ... 8 1 3]
 [6 7 0 ... 3 1 8]]
[[5 4 2 ... 7 2 1]
 [5 9 2 ... 8 9 6]
 [8 8 1 ... 5 1 3]
 ...
 [8 7 3 ... 7 2 1]
 [9 5 3 ... 9 2 4]
 [7 8 1 ... 4 2 9]]
[[0 0 0 ... 0 0 0]
 [5 9 2 ... 8 9 6]
 [0 0 0 ... 0 0 0]
 ...
 [8 7 3 ... 7 2 1]
 [0 0 0 ... 0 0 0]
 [7 8 1 ... 4 2 9]]
[[0 0 0 ... 0 0 0]
 [5 0 2 ... 0 9 0]
 [0 0 0 ... 0 0 0]
 ...
 [8 0 3 ... 0 2 0]
 [0 0 0 ... 0 0 0]
 [7 0 1 ... 0 2 0]]
